// ignore: file_names
List hiraganaLst = [
  {"jp": "あ", "eng": "a"},
  {"jp": "い", "eng": "i"},
  {"jp": "う", "eng": "u"},
  {"jp": "え", "eng": "e"},
  {"jp": "お", "eng": "o"},
  {"jp": "か", "eng": "ka"},
  {"jp": "き", "eng": "ki"},
  {"jp": "く", "eng": "ku"},
  {"jp": "け", "eng": "ke"},
  {"jp": "こ", "eng": "ko"},
  {"jp": "さ", "eng": "sa"},
  {"jp": "し", "eng": "shi"},
  {"jp": "す", "eng": "su"},
  {"jp": "せ", "eng": "se"},
  {"jp": "そ", "eng": "so"},
  {"jp": "た", "eng": "ta"},
  {"jp": "ち", "eng": "chi"},
  {"jp": "つ", "eng": "tsu"},
  {"jp": "て", "eng": "te"},
  {"jp": "と", "eng": "to"},
  {"jp": "な", "eng": "na"},
  {"jp": "に", "eng": "ni"},
  {"jp": "ぬ", "eng": "nu"},
  {"jp": "ね", "eng": "ne"},
  {"jp": "の", "eng": "no"},
  {"jp": "は", "eng": "ha"},
  {"jp": "ひ", "eng": "hi"},
  {"jp": "ふ", "eng": "fu"},
  {"jp": "へ", "eng": "he"},
  {"jp": "ほ", "eng": "ho"},
  {"jp": "ま", "eng": "ma"},
  {"jp": "み", "eng": "mi"},
  {"jp": "む", "eng": "mu"},
  {"jp": "め", "eng": "me"},
  {"jp": "も", "eng": "mo"},

  {"jp": "や", "eng": "ya"},
  {"jp": "", "eng": ""},
  {"jp": "ゆ", "eng": "yu"},
  {"jp": "", "eng": ""},
  {"jp": "よ", "eng": "yo"},

  {"jp": "ら", "eng": "ra"},
  {"jp": "り", "eng": "ri"},
  {"jp": "る", "eng": "ru"},
  {"jp": "れ", "eng": "re"},
  {"jp": "ろ", "eng": "ro"},

  {"jp": "わ", "eng": "wa"},
  {"jp": "", "eng": ""},
  {"jp": "を", "eng": "wo"},
  {"jp": "", "eng": ""},
  {"jp": "ん", "eng": "n"},
  
  {"jp": "が", "eng": "ga"},
  {"jp": "ぎ", "eng": "gi"},
  {"jp": "ぐ", "eng": "gu"},
  {"jp": "げ", "eng": "ge"},
  {"jp": "ご", "eng": "go"},

  {"jp": "ざ", "eng": "za"},
  {"jp": "じ", "eng": "ji"},
  {"jp": "ず", "eng": "zu"},
  {"jp": "ぜ", "eng": "ze"},
  {"jp": "ぞ", "eng": "zo"},

  {"jp": "だ", "eng": "da"},
  {"jp": "ぢ", "eng": "ji"},
  {"jp": "づ", "eng": "zu"},
  {"jp": "で", "eng": "de"},
  {"jp": "ど", "eng": "do"},

  {"jp": "ば", "eng": "ba"},
  {"jp": "び", "eng": "bi"},
  {"jp": "ぶ", "eng": "bu"},
  {"jp": "べ", "eng": "be"},
  {"jp": "ぼ", "eng": "bo"},

  {"jp": "ぱ", "eng": "pa"},
  {"jp": "ぴ", "eng": "pi"},
  {"jp": "ぷ", "eng": "pu"},
  {"jp": "ぺ", "eng": "pe"},
  {"jp": "ぽ", "eng": "po"},
  
  {"jp": "", "eng": ""},
  {"jp": "きゃ", "eng": "kya"},
  {"jp": "きゅ", "eng": "kyu"},
  {"jp": "きょ", "eng": "kyo"},
  {"jp": "", "eng": ""},

  {"jp": "", "eng": ""},
  {"jp": "しゃ", "eng": "sha"},
  {"jp": "しゅ", "eng": "shu"},
  {"jp": "しょ", "eng": "sho"},
  {"jp": "", "eng": ""},

  {"jp": "", "eng": ""},
  {"jp": "ちゃ", "eng": "cha"},
  {"jp": "ちゅ", "eng": "chu"},
  {"jp": "ちょ", "eng": "cho"},
  {"jp": "", "eng": ""},
  
  {"jp": "", "eng": ""},
  {"jp": "にゃ", "eng": "nya"},
  {"jp": "にゅ", "eng": "nyu"},
  {"jp": "にょ", "eng": "nyo"},
  {"jp": "", "eng": ""},

  {"jp": "", "eng": ""},
  {"jp": "ひゃ", "eng": "hya"},
  {"jp": "ひゅ", "eng": "hyu"},
  {"jp": "ひょ", "eng": "hyo"},
  {"jp": "", "eng": ""},

  {"jp": "", "eng": ""},
  {"jp": "みゃ", "eng": "mya"},
  {"jp": "みゅ", "eng": "myu"},
  {"jp": "みょ", "eng": "myo"},
  {"jp": "", "eng": ""},

  {"jp": "", "eng": ""},
  {"jp": "りゃ", "eng": "rya"},
  {"jp": "りゅ", "eng": "ryu"},
  {"jp": "りょ", "eng": "ryo"},
  {"jp": "", "eng": ""},

  {"jp": "", "eng": ""},
  {"jp": "ぎゃ", "eng": "gya"},
  {"jp": "ぎゅ", "eng": "gyu"},
  {"jp": "ぎょ", "eng": "gyo"},
  {"jp": "", "eng": ""},

  {"jp": "", "eng": ""},
  {"jp": "じゃ", "eng": "ja"},
  {"jp": "じゅ", "eng": "ju"},
  {"jp": "じょ", "eng": "jo"},
  {"jp": "", "eng": ""},

  {"jp": "", "eng": ""},
  {"jp": "びゃ", "eng": "bya"},
  {"jp": "びゅ", "eng": "byu"},
  {"jp": "びょ", "eng": "byo"},
  {"jp": "", "eng": ""},

  {"jp": "", "eng": ""},
  {"jp": "ぴゃ", "eng": "pya"},
  {"jp": "ぴゅ", "eng": "pyu"},
  {"jp": "ぴょ", "eng": "pyo"},
  {"jp": "", "eng": ""},
];


// ignore: file_names
List katakanaLst = [
  {"jp": "ア", "eng": "a"},
  {"jp": "イ", "eng": "i"},
  {"jp": "ウ", "eng": "u"},
  {"jp": "エ", "eng": "e"},
  {"jp": "オ", "eng": "o"},
  {"jp": "カ", "eng": "ka"},
  {"jp": "キ", "eng": "ki"},
  {"jp": "ク", "eng": "ku"},
  {"jp": "ケ", "eng": "ke"},
  {"jp": "コ", "eng": "ko"},
  {"jp": "サ", "eng": "sa"},
  {"jp": "シ", "eng": "shi"},
  {"jp": "ス", "eng": "su"},
  {"jp": "セ", "eng": "se"},
  {"jp": "ソ", "eng": "so"},
  {"jp": "タ", "eng": "ta"},
  {"jp": "チ", "eng": "chi"},
  {"jp": "ツ", "eng": "tsu"},
  {"jp": "テ", "eng": "te"},
  {"jp": "ト", "eng": "to"},
  {"jp": "ナ", "eng": "na"},
  {"jp": "ニ", "eng": "ni"},
  {"jp": "ヌ", "eng": "nu"},
  {"jp": "ネ", "eng": "ne"},
  {"jp": "ノ", "eng": "no"},
  {"jp": "ハ", "eng": "ha"},
  {"jp": "ヒ", "eng": "hi"},
  {"jp": "フ", "eng": "fu"},
  {"jp": "ヘ", "eng": "he"},
  {"jp": "ホ", "eng": "ho"},
  {"jp": "マ", "eng": "ma"},
  {"jp": "ミ", "eng": "mi"},
  {"jp": "ム", "eng": "mu"},
  {"jp": "メ", "eng": "me"},
  {"jp": "モ", "eng": "mo"},

  {"jp": "ヤ", "eng": "ya"},
  {"jp": "", "eng": ""},
  {"jp": "ユ", "eng": "yu"},
  {"jp": "", "eng": ""},
  {"jp": "ヨ", "eng": "yo"},

  {"jp": "ラ", "eng": "ra"},
  {"jp": "リ", "eng": "ri"},
  {"jp": "ル", "eng": "ru"},
  {"jp": "レ", "eng": "re"},
  {"jp": "ロ", "eng": "ro"},

  {"jp": "ワ", "eng": "wa"},
  {"jp": "", "eng": ""},
  {"jp": "ヲ", "eng": "wo"},
  {"jp": "", "eng": ""},
  {"jp": "ン", "eng": "n"},
  
  {"jp": "ガ", "eng": "ga"},
  {"jp": "ギ", "eng": "gi"},
  {"jp": "グ", "eng": "gu"},
  {"jp": "ゲ", "eng": "ge"},
  {"jp": "ゴ", "eng": "go"},

  {"jp": "ザ", "eng": "za"},
  {"jp": "ジ", "eng": "ji"},
  {"jp": "ズ", "eng": "zu"},
  {"jp": "ゼ", "eng": "ze"},
  {"jp": "ゾ", "eng": "zo"},

  {"jp": "ダ", "eng": "da"},
  {"jp": "ヂ", "eng": "ji"},
  {"jp": "ヅ", "eng": "zu"},
  {"jp": "デ", "eng": "de"},
  {"jp": "ド", "eng": "do"},

  {"jp": "バ", "eng": "ba"},
  {"jp": "ビ", "eng": "bi"},
  {"jp": "ブ", "eng": "bu"},
  {"jp": "ベ", "eng": "be"},
  {"jp": "ボ", "eng": "bo"},

  {"jp": "パ", "eng": "pa"},
  {"jp": "ピ", "eng": "pi"},
  {"jp": "プ", "eng": "pu"},
  {"jp": "ぺ", "eng": "pe"},
  {"jp": "ポ", "eng": "po"},
  
  {"jp": "", "eng": ""},
  {"jp": "キャ", "eng": "kya"},
  {"jp": "キュ", "eng": "kyu"},
  {"jp": "キョ", "eng": "kyo"},
  {"jp": "", "eng": ""},

  {"jp": "", "eng": ""},
  {"jp": "シャ", "eng": "sha"},
  {"jp": "シュ", "eng": "shu"},
  {"jp": "ショ", "eng": "sho"},
  {"jp": "", "eng": ""},

  {"jp": "", "eng": ""},
  {"jp": "チャ", "eng": "cha"},
  {"jp": "チュ", "eng": "chu"},
  {"jp": "チョ", "eng": "cho"},
  {"jp": "", "eng": ""},
  
  {"jp": "", "eng": ""},
  {"jp": "ニャ", "eng": "nya"},
  {"jp": "ニュ", "eng": "nyu"},
  {"jp": "ニョ", "eng": "nyo"},
  {"jp": "", "eng": ""},

  {"jp": "", "eng": ""},
  {"jp": "ヒャ", "eng": "hya"},
  {"jp": "ヒュ", "eng": "hyu"},
  {"jp": "ヒョ", "eng": "hyo"},
  {"jp": "", "eng": ""},

  {"jp": "", "eng": ""},
  {"jp": "ミャ", "eng": "mya"},
  {"jp": "ミュ", "eng": "myu"},
  {"jp": "ミョ", "eng": "myo"},
  {"jp": "", "eng": ""},

  {"jp": "", "eng": ""},
  {"jp": "リャ", "eng": "rya"},
  {"jp": "リュ", "eng": "ryu"},
  {"jp": "リョ", "eng": "ryo"},
  {"jp": "", "eng": ""},

  {"jp": "", "eng": ""},
  {"jp": "ギャ", "eng": "gya"},
  {"jp": "ギュ", "eng": "gyu"},
  {"jp": "ギョ", "eng": "gyo"},
  {"jp": "", "eng": ""},

  {"jp": "", "eng": ""},
  {"jp": "ジャ", "eng": "ja"},
  {"jp": "ジュ", "eng": "ju"},
  {"jp": "ジョ", "eng": "jo"},
  {"jp": "", "eng": ""},

  {"jp": "", "eng": ""},
  {"jp": "ビャ", "eng": "bya"},
  {"jp": "ビュ", "eng": "byu"},
  {"jp": "ビョ", "eng": "byo"},
  {"jp": "", "eng": ""},

  {"jp": "", "eng": ""},
  {"jp": "ピャ", "eng": "pya"},
  {"jp": "ピュ", "eng": "pyu"},
  {"jp": "ピョ", "eng": "pyo"},
  {"jp": "", "eng": ""},
];
