// ignore: file_names
List hiraganaLst = [
  {"jp": "あ", "eng": "a", "img": ""},
  {"jp": "い", "eng": "i", "img": ""},
  {"jp": "う", "eng": "u", "img": ""},
  {"jp": "え", "eng": "e", "img": ""},
  {"jp": "お", "eng": "o", "img": ""},
  {"jp": "か", "eng": "ka", "img": ""},
  {"jp": "き", "eng": "ki", "img": ""},
  {"jp": "く", "eng": "ku", "img": ""},
  {"jp": "け", "eng": "ke", "img": ""},
  {"jp": "こ", "eng": "ko", "img": ""},
  {"jp": "さ", "eng": "sa", "img": ""},
  {"jp": "し", "eng": "shi", "img": ""},
  {"jp": "す", "eng": "su", "img": ""},
  {"jp": "せ", "eng": "se", "img": ""},
  {"jp": "そ", "eng": "so", "img": ""},
  {"jp": "た", "eng": "ta", "img": ""},
  {"jp": "ち", "eng": "chi", "img": ""},
  {"jp": "つ", "eng": "tsu", "img": ""},
  {"jp": "て", "eng": "te", "img": ""},
  {"jp": "と", "eng": "to", "img": ""},
  {"jp": "な", "eng": "na", "img": ""},
  {"jp": "に", "eng": "ni", "img": ""},
  {"jp": "ぬ", "eng": "nu", "img": ""},
  {"jp": "ね", "eng": "ne", "img": ""},
  {"jp": "の", "eng": "no", "img": ""},
  {"jp": "は", "eng": "ha", "img": ""},
  {"jp": "ひ", "eng": "hi", "img": ""},
  {"jp": "ふ", "eng": "fu", "img": ""},
  {"jp": "へ", "eng": "he", "img": ""},
  {"jp": "ほ", "eng": "ho", "img": ""},
  {"jp": "ま", "eng": "ma", "img": ""},
  {"jp": "み", "eng": "mi", "img": ""},
  {"jp": "む", "eng": "mu", "img": ""},
  {"jp": "め", "eng": "me", "img": ""},
  {"jp": "も", "eng": "mo", "img": ""},

  {"jp": "や", "eng": "ya", "img": ""},
  {"jp": "", "eng": "", "img": ""},
  {"jp": "ゆ", "eng": "yu", "img": ""},
  {"jp": "", "eng": "", "img": ""},
  {"jp": "よ", "eng": "yo", "img": ""},

  {"jp": "ら", "eng": "ra", "img": ""},
  {"jp": "り", "eng": "ri", "img": ""},
  {"jp": "る", "eng": "ru", "img": ""},
  {"jp": "れ", "eng": "re", "img": ""},
  {"jp": "ろ", "eng": "ro", "img": ""},

  {"jp": "わ", "eng": "wa", "img": ""},
  {"jp": "", "eng": "", "img": ""},
  {"jp": "を", "eng": "wo", "img": ""},
  {"jp": "", "eng": "", "img": ""},
  {"jp": "ん", "eng": "n", "img": ""},
  
  {"jp": "が", "eng": "ga", "img": ""},
  {"jp": "ぎ", "eng": "gi", "img": ""},
  {"jp": "ぐ", "eng": "gu", "img": ""},
  {"jp": "げ", "eng": "ge", "img": ""},
  {"jp": "ご", "eng": "go", "img": ""},

  {"jp": "ざ", "eng": "za", "img": ""},
  {"jp": "じ", "eng": "ji", "img": ""},
  {"jp": "ず", "eng": "zu", "img": ""},
  {"jp": "ぜ", "eng": "ze", "img": ""},
  {"jp": "ぞ", "eng": "zo", "img": ""},

  {"jp": "だ", "eng": "da", "img": ""},
  {"jp": "ぢ", "eng": "ji", "img": ""},
  {"jp": "づ", "eng": "zu", "img": ""},
  {"jp": "で", "eng": "de", "img": ""},
  {"jp": "ど", "eng": "do", "img": ""},

  {"jp": "ば", "eng": "ba", "img": ""},
  {"jp": "び", "eng": "bi", "img": ""},
  {"jp": "ぶ", "eng": "bu", "img": ""},
  {"jp": "べ", "eng": "be", "img": ""},
  {"jp": "ぼ", "eng": "bo", "img": ""},

  {"jp": "ぱ", "eng": "pa", "img": ""},
  {"jp": "ぴ", "eng": "pi", "img": ""},
  {"jp": "ぷ", "eng": "pu", "img": ""},
  {"jp": "ぺ", "eng": "pe", "img": ""},
  {"jp": "ぽ", "eng": "po", "img": ""},
  
  {"jp": "", "eng": "", "img": ""},
  {"jp": "きゃ", "eng": "kya", "img": ""},
  {"jp": "きゅ", "eng": "kyu", "img": ""},
  {"jp": "きょ", "eng": "kyo", "img": ""},
  {"jp": "", "eng": "", "img": ""},

  {"jp": "", "eng": "", "img": ""},
  {"jp": "しゃ", "eng": "sha", "img": ""},
  {"jp": "しゅ", "eng": "shu", "img": ""},
  {"jp": "しょ", "eng": "sho", "img": ""},
  {"jp": "", "eng": "", "img": ""},

  {"jp": "", "eng": "", "img": ""},
  {"jp": "ちゃ", "eng": "cha", "img": ""},
  {"jp": "ちゅ", "eng": "chu", "img": ""},
  {"jp": "ちょ", "eng": "cho", "img": ""},
  {"jp": "", "eng": "", "img": ""},
  
  {"jp": "", "eng": "", "img": ""},
  {"jp": "にゃ", "eng": "nya", "img": ""},
  {"jp": "にゅ", "eng": "nyu", "img": ""},
  {"jp": "にょ", "eng": "nyo", "img": ""},
  {"jp": "", "eng": "", "img": ""},

  {"jp": "", "eng": "", "img": ""},
  {"jp": "ひゃ", "eng": "hya", "img": ""},
  {"jp": "ひゅ", "eng": "hyu", "img": ""},
  {"jp": "ひょ", "eng": "hyo", "img": ""},
  {"jp": "", "eng": "", "img": ""},

  {"jp": "", "eng": "", "img": ""},
  {"jp": "みゃ", "eng": "mya", "img": ""},
  {"jp": "みゅ", "eng": "myu", "img": ""},
  {"jp": "みょ", "eng": "myo", "img": ""},
  {"jp": "", "eng": "", "img": ""},

  {"jp": "", "eng": "", "img": ""},
  {"jp": "りゃ", "eng": "rya", "img": ""},
  {"jp": "りゅ", "eng": "ryu", "img": ""},
  {"jp": "りょ", "eng": "ryo", "img": ""},
  {"jp": "", "eng": "", "img": ""},

  {"jp": "", "eng": "", "img": ""},
  {"jp": "ぎゃ", "eng": "gya", "img": ""},
  {"jp": "ぎゅ", "eng": "gyu", "img": ""},
  {"jp": "ぎょ", "eng": "gyo", "img": ""},
  {"jp": "", "eng": "", "img": ""},

  {"jp": "", "eng": "", "img": ""},
  {"jp": "じゃ", "eng": "ja", "img": ""},
  {"jp": "じゅ", "eng": "ju", "img": ""},
  {"jp": "じょ", "eng": "jo", "img": ""},
  {"jp": "", "eng": "", "img": ""},

  {"jp": "", "eng": "", "img": ""},
  {"jp": "びゃ", "eng": "bya", "img": ""},
  {"jp": "びゅ", "eng": "byu", "img": ""},
  {"jp": "びょ", "eng": "byo", "img": ""},
  {"jp": "", "eng": "", "img": ""},

  {"jp": "", "eng": "", "img": ""},
  {"jp": "ぴゃ", "eng": "pya", "img": ""},
  {"jp": "ぴゅ", "eng": "pyu", "img": ""},
  {"jp": "ぴょ", "eng": "pyo", "img": ""},
  {"jp": "", "eng": "", "img": ""},
];


// ignore: file_names
List katakanaLst = [
  {"jp": "ア", "eng": "a", "img": "assets/alphabet/katakana/a.png"},
  {"jp": "イ", "eng": "i", "img": "assets/alphabet/katakana/i.png"},
  {"jp": "ウ", "eng": "u", "img": "assets/alphabet/katakana/u.png"},
  {"jp": "エ", "eng": "e", "img": "assets/alphabet/katakana/e.png"},
  {"jp": "オ", "eng": "o", "img": "assets/alphabet/katakana/o.png"},
  {"jp": "カ", "eng": "ka", "img": "assets/alphabet/katakana/ka.png"},
  {"jp": "キ", "eng": "ki", "img": "assets/alphabet/katakana/ki.png"},
  {"jp": "ク", "eng": "ku", "img": "assets/alphabet/katakana/ku.png"},
  {"jp": "ケ", "eng": "ke", "img": "assets/alphabet/katakana/ke.png"},
  {"jp": "コ", "eng": "ko", "img": "assets/alphabet/katakana/ko.png"},
  {"jp": "サ", "eng": "sa", "img": "assets/alphabet/katakana/sa.png"},
  {"jp": "シ", "eng": "shi", "img": "assets/alphabet/katakana/shi.png"},
  {"jp": "ス", "eng": "su", "img": "assets/alphabet/katakana/su.png"},
  {"jp": "セ", "eng": "se", "img": "assets/alphabet/katakana/se.png"},
  {"jp": "ソ", "eng": "so", "img": "assets/alphabet/katakana/so.png"},
  {"jp": "タ", "eng": "ta", "img": "assets/alphabet/katakana/ta.png"},
  {"jp": "チ", "eng": "chi", "img": "assets/alphabet/katakana/chi.png"},
  {"jp": "ツ", "eng": "tsu", "img": "assets/alphabet/katakana/tsu.png"},
  {"jp": "テ", "eng": "te", "img": "assets/alphabet/katakana/te.png"},
  {"jp": "ト", "eng": "to", "img": "assets/alphabet/katakana/to.png"},
  {"jp": "ナ", "eng": "na", "img": "assets/alphabet/katakana/na.png"},
  {"jp": "ニ", "eng": "ni", "img": "assets/alphabet/katakana/ni.png"},
  {"jp": "ヌ", "eng": "nu", "img": "assets/alphabet/katakana/nu.png"},
  {"jp": "ネ", "eng": "ne", "img": "assets/alphabet/katakana/ne.png"},
  {"jp": "ノ", "eng": "no", "img": "assets/alphabet/katakana/no.png"},
  {"jp": "ハ", "eng": "ha", "img": "assets/alphabet/katakana/ha.png"},
  {"jp": "ヒ", "eng": "hi", "img": "assets/alphabet/katakana/hi.png"},
  {"jp": "フ", "eng": "fu", "img": "assets/alphabet/katakana/fu.png"},
  {"jp": "ヘ", "eng": "he", "img": "assets/alphabet/katakana/he.png"},
  {"jp": "ホ", "eng": "ho", "img": "assets/alphabet/katakana/ho.png"},
  {"jp": "マ", "eng": "ma", "img": "assets/alphabet/katakana/ma.png"},
  {"jp": "ミ", "eng": "mi", "img": "assets/alphabet/katakana/mi.png"},
  {"jp": "ム", "eng": "mu", "img": "assets/alphabet/katakana/mu.png"},
  {"jp": "メ", "eng": "me", "img": "assets/alphabet/katakana/me.png"},
  {"jp": "モ", "eng": "mo", "img": "assets/alphabet/katakana/mo.png"},

  {"jp": "ヤ", "eng": "ya", "img": "assets/alphabet/katakana/ya.png"},
  {"jp": "", "eng": "", "img": ""},
  {"jp": "ユ", "eng": "yu", "img": "assets/alphabet/katakana/yu.png"},
  {"jp": "", "eng": "", "img": ""},
  {"jp": "ヨ", "eng": "yo", "img": "assets/alphabet/katakana/yo.png"},

  {"jp": "ラ", "eng": "ra", "img": "assets/alphabet/katakana/ra.png"},
  {"jp": "リ", "eng": "ri", "img": "assets/alphabet/katakana/ri.png"},
  {"jp": "ル", "eng": "ru", "img": "assets/alphabet/katakana/ru.png"},
  {"jp": "レ", "eng": "re", "img": "assets/alphabet/katakana/re.png"},
  {"jp": "ロ", "eng": "ro", "img": "assets/alphabet/katakana/ro.png"},

  {"jp": "ワ", "eng": "wa", "img": "assets/alphabet/katakana/wa.png"},
  {"jp": "", "eng": "", "img": ""},
  {"jp": "ヲ", "eng": "wo", "img": "assets/alphabet/katakana/wo.png"},
  {"jp": "", "eng": "", "img": ""},
  {"jp": "ン", "eng": "n", "img": "assets/alphabet/katakana/n.png"},
  
  {"jp": "ガ", "eng": "ga", "img": ""},
  {"jp": "ギ", "eng": "gi", "img": ""},
  {"jp": "グ", "eng": "gu", "img": ""},
  {"jp": "ゲ", "eng": "ge", "img": ""},
  {"jp": "ゴ", "eng": "go", "img": ""},

  {"jp": "ザ", "eng": "za", "img": ""},
  {"jp": "ジ", "eng": "ji", "img": ""},
  {"jp": "ズ", "eng": "zu", "img": ""},
  {"jp": "ゼ", "eng": "ze", "img": ""},
  {"jp": "ゾ", "eng": "zo", "img": ""},

  {"jp": "ダ", "eng": "da", "img": ""},
  {"jp": "ヂ", "eng": "ji", "img": ""},
  {"jp": "ヅ", "eng": "zu", "img": ""},
  {"jp": "デ", "eng": "de", "img": ""},
  {"jp": "ド", "eng": "do", "img": ""},

  {"jp": "バ", "eng": "ba", "img": ""},
  {"jp": "ビ", "eng": "bi", "img": ""},
  {"jp": "ブ", "eng": "bu", "img": ""},
  {"jp": "ベ", "eng": "be", "img": ""},
  {"jp": "ボ", "eng": "bo", "img": ""},

  {"jp": "パ", "eng": "pa", "img": ""},
  {"jp": "ピ", "eng": "pi", "img": ""},
  {"jp": "プ", "eng": "pu", "img": ""},
  {"jp": "ぺ", "eng": "pe", "img": ""},
  {"jp": "ポ", "eng": "po", "img": ""},
  
  {"jp": "", "eng": "", "img": ""},
  {"jp": "キャ", "eng": "kya", "img": ""},
  {"jp": "キュ", "eng": "kyu", "img": ""},
  {"jp": "キョ", "eng": "kyo", "img": ""},
  {"jp": "", "eng": "", "img": ""},

  {"jp": "", "eng": "", "img": ""},
  {"jp": "シャ", "eng": "sha", "img": ""},
  {"jp": "シュ", "eng": "shu", "img": ""},
  {"jp": "ショ", "eng": "sho", "img": ""},
  {"jp": "", "eng": "", "img": ""},

  {"jp": "", "eng": "", "img": ""},
  {"jp": "チャ", "eng": "cha", "img": ""},
  {"jp": "チュ", "eng": "chu", "img": ""},
  {"jp": "チョ", "eng": "cho", "img": ""},
  {"jp": "", "eng": "", "img": ""},
  
  {"jp": "", "eng": "", "img": ""},
  {"jp": "ニャ", "eng": "nya", "img": ""},
  {"jp": "ニュ", "eng": "nyu", "img": ""},
  {"jp": "ニョ", "eng": "nyo", "img": ""},
  {"jp": "", "eng": "", "img": ""},

  {"jp": "", "eng": "", "img": ""},
  {"jp": "ヒャ", "eng": "hya", "img": ""},
  {"jp": "ヒュ", "eng": "hyu", "img": ""},
  {"jp": "ヒョ", "eng": "hyo", "img": ""},
  {"jp": "", "eng": "", "img": ""},

  {"jp": "", "eng": "", "img": ""},
  {"jp": "ミャ", "eng": "mya", "img": ""},
  {"jp": "ミュ", "eng": "myu", "img": ""},
  {"jp": "ミョ", "eng": "myo", "img": ""},
  {"jp": "", "eng": "", "img": ""},

  {"jp": "", "eng": "", "img": ""},
  {"jp": "リャ", "eng": "rya", "img": ""},
  {"jp": "リュ", "eng": "ryu", "img": ""},
  {"jp": "リョ", "eng": "ryo", "img": ""},
  {"jp": "", "eng": "", "img": ""},

  {"jp": "", "eng": "", "img": ""},
  {"jp": "ギャ", "eng": "gya", "img": ""},
  {"jp": "ギュ", "eng": "gyu", "img": ""},
  {"jp": "ギョ", "eng": "gyo", "img": ""},
  {"jp": "", "eng": "", "img": ""},

  {"jp": "", "eng": "", "img": ""},
  {"jp": "ジャ", "eng": "ja", "img": ""},
  {"jp": "ジュ", "eng": "ju", "img": ""},
  {"jp": "ジョ", "eng": "jo", "img": ""},
  {"jp": "", "eng": "", "img": ""},

  {"jp": "", "eng": "", "img": ""},
  {"jp": "ビャ", "eng": "bya", "img": ""},
  {"jp": "ビュ", "eng": "byu", "img": ""},
  {"jp": "ビョ", "eng": "byo", "img": ""},
  {"jp": "", "eng": "", "img": ""},

  {"jp": "", "eng": "", "img": ""},
  {"jp": "ピャ", "eng": "pya", "img": ""},
  {"jp": "ピュ", "eng": "pyu", "img": ""},
  {"jp": "ピョ", "eng": "pyo", "img": ""},
  {"jp": "", "eng": "", "img": ""},
];
